### ISSUE TITLE
Enabling compatability mode (--compat)

### ISSUE THREAD

**Issue by keiviv** [sublimelsp/LSP-Deno#11]
Is it possible to enable the [--compat](https://deno.land/manual@v1.17.0/npm_nodejs/compatibility_mode) mode?
Deno exits with `1` if it's added to the `command` section of the settings. (The required `unstable` flag was enabled, so it's not the issue).
Is there any other way to pass the flag?

**Comment by predragnikolic** [comment]
> Is it possible to enable the [--compat](https://deno.land/manual@v1.17.0/npm_nodejs/compatibility_mode) mode?

I do not know the answer to that question. 

But run the following in the terminal, but it exists with 1.
```
λ  ~  deno --version
deno 1.21.1 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.17
typescript 4.6.2
λ  ~  deno lsp --compat
error: Found argument '--compat' which wasn't expected, or isn't valid in this context

	If you tried to supply `--compat` as a value rather than a flag, use `-- --compat`

USAGE:
    deno lsp [OPTIONS]

For more information try --help

λ  ~  
```

Why do you need to pass in the `--compat` mode in the first place?
What are you trying to achieve, or what problem are you trying to solve.

**Comment by predragnikolic** [comment]
> It runs without issues, and is a very useful mode.

Are you sure? 
The `deno run` command can work with `--compat --unstable`,        
but the `deno lsp` command can only accept the --unstable at the moment.

I run the following command but it exits:
```
λ  denoFmt main ✓ deno lsp --compat --unstable            
error: Found argument '--compat' which wasn't expected, or isn't valid in this context

	If you tried to supply `--compat` as a value rather than a flag, use `-- --compat`

USAGE:
    deno lsp [OPTIONS]

For more information try --help
```

Because the `deno lsp` command only supports the following commands: --quiet and --unstable
```
λ  denoFmt main ✓ deno lsp --help
deno-lsp 
The 'deno lsp' subcommand provides a way for code editors and IDEs to
interact with Deno using the Language Server Protocol. Usually humans do not
use this subcommand directly. For example, 'deno lsp' can provide IDEs with
go-to-definition support and automatic code formatting.

How to connect various editors and IDEs to 'deno lsp':
https://deno.land/manual/getting_started/setup_your_environment#editors-and-ides

USAGE:
    deno lsp [OPTIONS]

OPTIONS:
    -h, --help
            Print help information

    -q, --quiet
            Suppress diagnostic output

        --unstable
            Enable unstable features and APIs
```
