### ISSUE TITLE
Can't load config

### ISSUE THREAD

**Issue by keiviv** [sublimelsp/LSP-Deno#12]
I cannot make `"deno.config": "path/to/cfg.json"` to work. Tried both absolute and relative paths.
The config works when called directly: `deno fmt --config`, but is ignored when in the settings and using the LSP format — the `indentWidth` etc is ignored.

Config:
```json
{
  "fmt": {
    "options": {
      "useTabs": false,
      "lineWidth": 80,
      "indentWidth": 4,
      "singleQuote": true,
      "proseWrap": "preserve"
    }
  }
}
```

**Comment by predragnikolic** [comment]
Hello @keiviv :wave: 

Here is the minimal repo https://github.com/predragnikolic/deno-config-bug that showcases that this works.

Open the command palette and type: `Preferences: LSP-deno Settings`,
and specify the `deno.config` as bellow.
```jsonc
// Settings in here override those in "LSP-Deno/LSP-Deno.sublime-settings"

{
	"enabled": true,
	"command": [
		"/home/predragnikolic/.deno/bin/deno",
		"lsp"
	],
	"settings": {
		"deno.config": "${folder}/cfg.json" // is a [template variable](http://www.sublimetext.com/docs/build_systems.html#variables) ${folder}, and it will be replaced with the opened directory
	}
}
```

If you open the `hello.ts` file, 
and run `LSP format file` from the command palette, 
LSP will format the file according to the `fmt` options specified in the cfg.json file.

----

FWIW, here is one tip that the Deno docs mention:
https://deno.land/manual/getting_started/configuration_file
> The configuration file supports .json and .jsonc extensions. **We recommend to use deno.json or deno.jsonc as a file name**, as an automatic lookup of this file is planned for the upcoming releases.

**Comment by predragnikolic** [comment]
Feel free to reopen the issue if you still have issues.
