### ISSUE TITLE
Error: No such file or directory "deno"

### ISSUE THREAD

**Issue by HazardousDeveloper** [sublimelsp/LSP-Deno#15]
I've installed Deno and LSP but whenever I try to enable the Deno language server, it throws an error stated in the title of this issue.

OS: Linux Mint 21.2 Cinnamon

(My user configuration is the default one)

**Comment by rchl** [comment]
Deno binary needs to be available on the PATH in context of Sublime Text. Check https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers on how to solve it.
