### ISSUE TITLE
Project settings not overriding language server settings

### ISSUE THREAD

**Issue by RevanProdigalKnight** [sublimelsp/LSP-Deno#2]
**Describe the bug**
I'm not sure if this is a bug or user error, but my project settings for Deno import maps are not overriding default language server settings for LSP-Deno.

**To Reproduce**
1. Create a Deno import-map file, e.g.:

    ```json
    {
      "x/": "https://deno.land/x/"
    }
    ```

2. Create a new typescript file and attempt to import something using the import mapping:

    ```ts
    import { Application, Router } from 'x/oak/mod.ts';
    ```

3. LSP-Deno reports error:

    ```txt
    relative import path "x/oak/mod.ts" not prefixed with / or ./ or ../ Imported from "file:///path/to/file.ts"
    ```

**Expected behavior**
No error is reported and type checking works properly as though the import path were `https://deno.land/x/oak/mod.ts`

**Environment (please complete the following information):**
- OS: Windows 10
- Sublime Text version: 4107
- LSP version: 1.6.1
- Language servers used: Deno

**Additional context**
My sublime-project file is as follows (the documentation and issues I looked at gave confusing and/or conflicting directions as to where to put the setting so I have tried everything I can think of to get it to work, none of these do):

```json
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "deno.importMap": "./import-map.json",
    "LSP": {
      "deno.importMap": "./import-map.json",
      "clients": {
        "deno": {
          "deno.importMap": "./import-map.json",
          "settings": {
            "deno.importMap": "./import-map.json"
          }
        }
      },
      "deno": {
        "deno.importMap": "./import-map.json",
        "settings": {
          "deno.importMap": "./import-map.json"
        }
      }
    }
  }
}
```

**Comment by rwols** [comment]
Thanks for using LSP-Deno.

As @rchl mentioned your json structure in your .sublime-settings needs to look like this:

```jsonc
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "LSP":
        {
            "Deno":
            {
                "settings":
                {
                    "deno.unstable": true,
                    "deno.importMap": "./import_map.json"
                }
            }
        }
    }
}
```

The docs mention that import maps are an unstable feature: https://deno.land/manual@v1.6.0/linking_to_external_code/import_maps

So you may also want to set `unstable: true` in the initialization options: Run _Preferences: LSP-Deno Settings` from the command palette and put

```jsonc
// Settings in here override those in "LSP-Deno/LSP-Deno.sublime-settings"
{
    "initializationOptions":
    {
        "unstable": true,
        "lint": true,
        "enable": true
    }
}
```

**Comment by RevanProdigalKnight** [comment]
Okay, I have now fixed my `.sublime-settings` file using LSP-json (I was not aware of its ability to determine whether or not my configs are correct, I think it would be a good idea to list that as a suggested companion to LSP somewhere in the documentation), but the import map still isn't working.

I know that my import map works because I set it up using VS Code while I waited to be able to use LSP-Deno in Sublime Text, and it doesn't complain about any of my imports. (I have Deno 1.9.2 installed, and the docs for that version no longer say that import maps are experimental)

VS Code:
![image](https://user-images.githubusercontent.com/5728037/122675925-f0caf880-d198-11eb-8687-96abf17730c4.png)

Sublime Text:
![image](https://user-images.githubusercontent.com/5728037/122675953-122be480-d199-11eb-8493-431d3e907515.png)

Here is the output from the LSP Log Panel:

![image](https://user-images.githubusercontent.com/5728037/122675777-3509c900-d198-11eb-8ab1-e36c0f05dee1.png)

**Comment by rwols** [comment]
Missing field "enable"? Looks like it really wants those vscode-specific settings as well. I've created a pull request that adds those settings. I now get an error about a non-existing import map, which is expected. Thanks for the bug report.

**Comment by rwols** [comment]
tag 1.0.1 will show up on package control soon: https://github.com/sublimelsp/LSP-Deno/releases/tag/1.0.1
