### ISSUE TITLE
deno.enable is not working

### ISSUE THREAD

**Issue by hronro** [sublimelsp/LSP-Deno#4]
it seems `LSP-Deno` and `LSP-typescript` are enabled at the same time.

![CleanShot 2021-06-25 at 11 15 42@2x](https://user-images.githubusercontent.com/15059605/123364303-c4531a00-d5a6-11eb-96b2-2053d78a699c.png)

And here is my `.sublime-project`:

```JSON
{
	"folders": 	[
		{ "path": "." }
	],
	"settings": {
		"LSP": {
			"Deno": {
				"settings": {
					"deno.enable": true
				}
			}
		}
	}
}
```

**Comment by rchl** [comment]
It might be that that setting has to be handled by the helper package. Someone would need to check the vscode extension code.

But you can instead use `enabled` setting which is non-server specific.

You would set `"enabled": false"` in `Preferences: LSP-Deno Settings` and then this in project settings:

```js
{
	"folders": 	[
		{ "path": "." }
	],
	"settings": {
		"LSP": {
			"Deno": {
				"enabled": true,
			}
		}
	}
}
```

**Comment by rchl** [comment]
I did a quick check and we actually need `deno.enable` setting since it enables majority of the functionality.
Also we should probably enable `deno.lint` by default since the start of the server is controlled by the global `enabled` anyway.
