### ISSUE TITLE
triple-backtick code blocks are shown verbatim in the Signature Help popup

### ISSUE THREAD

**Issue by frou** [sublimelsp/LSP-Deno#9]
<img width="571" alt="Screenshot 2021-11-01 at 12 18 39" src="https://user-images.githubusercontent.com/172663/139670732-bcbe1840-7531-452f-91cb-68d26e05f453.png">

I'm not sure how feature-complete LSP's Signature Help popup is supposed to be, but in this instance, if that block was rendered in monospace (doesn't necessarily need to be syntax highlighted) it would be a lot better.

---

Deno v1.15.3
ST 4121 + LSP v1.13.0

**Comment by rchl** [comment]
It's a server issue. It returns the documention as plain text rather than in `MarkupContent`.

```
{
  "activeParameter": 0,
  "activeSignature": 0,
  "signatures": [
    {
      "documentation": "Open a file and resolve to an instance of `Deno.File`.  The\nfile does not need to previously exist if using the `create` or `createNew`\nopen options.  It is the callers responsibility to close the file when finished\nwith it.\n\n```ts\nconst file = await Deno.open(\"/foo/bar.txt\", { read: true, write: true });\n// Do work with file\nDeno.close(file.rid);\n```\n\nRequires `allow-read` and/or `allow-write` permissions depending on options.",
      "label": "open(path: string | URL, options?: Deno.OpenOptions | undefined): Promise<Deno.File>",
      "parameters": [
        {
          "documentation": "",
          "label": "path: string | URL"
        },
        {
          "documentation": "",
          "label": "options?: Deno.OpenOptions | undefined"
        }
      ]
    }
  ]
}
```

**Comment by frou** [comment]
Thanks - I will report it to them and post the link here

**Comment by frou** [comment]
https://github.com/denoland/deno/issues/12620

**Comment by lucacasonato** [comment]
Fixed now upstream 😊
